/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Data.AdministratorFileDB;
import Hospital.Administrator;
import javax.swing.JTable;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class AdministratorUI extends javax.swing.JFrame {
    
    private Administrator admin; 
    private DefaultTableModel tblModel;
    private AdministratorFileDB AfDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdministratorUI.class.getName());

    /**
     * Creates new form AdministratorUI
     */
    public AdministratorUI() {
        initComponents();
        setLocationRelativeTo(this);
        AfDB=new AdministratorFileDB();
        tblModel=new DefaultTableModel();
        tblAdmin.setModel(tblModel);
        tblModel.addColumn("Admin ID");
        tblModel.addColumn("Last Name");
        tblModel.addColumn("Gender");
        tblModel.addColumn("Address");
        tblModel.addColumn("Access Level");
        tblModel.addColumn("Department");
        tblModel.addColumn("Hire Date");
        tblModel.addColumn("Admin Type");
    }
    
    private boolean checkVal(){
        
        if (txtAdminID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Admin ID cannot be blank");
            return false;
        }
        if (txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Last Name cannot be blank");
            return false;
        }
        if (txtAddress.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Address cannot be blank");
            return false;
        }
        if (txtHireDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Hire Date cannot be blank");
            return false;
        }
        try{
             Date hireDate=Date.valueOf(txtHireDate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Date of Birth must be YYYY-MM-DD");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAdminID = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        txtAddress = new javax.swing.JTextField();
        cmbAccessLevel = new javax.swing.JComboBox<>();
        cmbDepartment = new javax.swing.JComboBox<>();
        txtHireDate = new javax.swing.JTextField();
        cmbAdminType = new javax.swing.JComboBox<>();
        AdminCmdPanel = new javax.swing.JPanel();
        btnAddData = new javax.swing.JButton();
        btnDeleteData = new javax.swing.JButton();
        btnUpdateData = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDisplayData = new javax.swing.JButton();
        btnFindData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdmin = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Admin Details");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Admin ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Gender");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Access Level");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Department");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Hire Date");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Admin Type");

        txtAdminID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonGroup1.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoMale.setText("Male");

        buttonGroup1.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoFemale.setText("Female");

        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbAccessLevel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAccessLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level A", "Level B", "Level C" }));

        cmbDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPD", "Emergency Department", "General Medicine", "General Surgery", "Pediatrics" }));

        txtHireDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbAdminType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAdminType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reception", "Medical Officer", "Finance Staff", "HR Staff" }));

        AdminCmdPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnAddData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddData.setText("Add Data");
        btnAddData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDataActionPerformed(evt);
            }
        });

        btnDeleteData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteData.setText("Delete Data");
        btnDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDataActionPerformed(evt);
            }
        });

        btnUpdateData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateData.setText("Update Data");
        btnUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDataActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnDisplayData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplayData.setText("Display Data");
        btnDisplayData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayDataActionPerformed(evt);
            }
        });

        btnFindData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFindData.setText("Find Data");
        btnFindData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminCmdPanelLayout = new javax.swing.GroupLayout(AdminCmdPanel);
        AdminCmdPanel.setLayout(AdminCmdPanelLayout);
        AdminCmdPanelLayout.setHorizontalGroup(
            AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCmdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFindData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdateData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        AdminCmdPanelLayout.setVerticalGroup(
            AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminCmdPanelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplayData)
                    .addComponent(btnAddData))
                .addGap(18, 18, 18)
                .addGroup(AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindData)
                    .addComponent(btnUpdateData))
                .addGap(18, 18, 18)
                .addGroup(AdminCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteData)
                    .addComponent(btnExit))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tblAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAdmin);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(242, 242, 242))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(txtAdminID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rdoMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(rdoFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDepartment, 0, 270, Short.MAX_VALUE)
                            .addComponent(cmbAccessLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHireDate)
                            .addComponent(cmbAdminType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)))
                .addComponent(AdminCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(txtAdminID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(rdoMale)
                            .addComponent(rdoFemale)
                            .addComponent(txtHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbAdminType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AdminCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminMouseClicked
        
    }//GEN-LAST:event_tblAdminMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDataActionPerformed
        // TODO add your handling code here:
        if (checkVal()){
            int adminID = Integer.valueOf(txtAdminID.getText());
            String lastName = txtLastName.getText();
            
            String gender="";
            if(rdoMale.isSelected()) {
                gender="Male";
            } else if (rdoFemale.isSelected()){
                gender="Female";
            } else {
                gender="";
            } 
            
            String address = txtAddress.getText();
            String accessLevel = cmbAccessLevel.getSelectedItem().toString();
            String department = cmbDepartment.getSelectedItem().toString();
            Date hireDate=Date.valueOf(txtHireDate.getText());
            String adminType = cmbAdminType.getSelectedItem().toString();

            admin = new Administrator (adminID, lastName, gender, address, accessLevel, department, hireDate, adminType);
            if (AfDB.addAdmin(admin))           
              JOptionPane.showMessageDialog(rootPane, "The Admin Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "The Admin Record is not added");
        }
    }//GEN-LAST:event_btnAddDataActionPerformed

    private void btnDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDataActionPerformed
        // TODO add your handling code here:
        int AID=Integer.valueOf(JOptionPane.showInputDialog("Enter Admin ID"));
        if(AfDB.deleteAdmin(AID))
            JOptionPane.showMessageDialog(rootPane, "Record is deleted");
        else
             JOptionPane.showMessageDialog(rootPane, "Record is not deleted");
    }//GEN-LAST:event_btnDeleteDataActionPerformed

    private void btnUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDataActionPerformed
        // TODO add your handling code here:
        if (checkVal()){
            int adminID = Integer.valueOf(txtAdminID.getText());
            String lastName = txtLastName.getText();
            
            String gender="";
            if(rdoMale.isSelected()) {
                gender="Male";
            } else if (rdoFemale.isSelected()){
                gender="Female";
            } else {
                gender="";
            } 
            
            String address = txtAddress.getText();
            String accessLevel = cmbAccessLevel.getSelectedItem().toString();
            String department = cmbDepartment.getSelectedItem().toString();
            Date hireDate=Date.valueOf(txtHireDate.getText());
            String adminType = cmbAdminType.getSelectedItem().toString();

            admin = new Administrator (adminID, lastName, gender, address, accessLevel, department, hireDate, adminType);
            if (AfDB.updateAdmin(admin))           
              JOptionPane.showMessageDialog(rootPane, "The Admin Record is updated");
            else
               JOptionPane.showMessageDialog(rootPane, "The Patient Record is not updated");
        }
    }//GEN-LAST:event_btnUpdateDataActionPerformed

    private void btnDisplayDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayDataActionPerformed
        // TO Display Data Button option
        ArrayList<Administrator> AList=AfDB.getAll();
        tblModel.setRowCount(0);
        for(Administrator admin:AList){
            int AID= admin.getAdminID();
            String lastName = admin.getLastName();
            String gender = admin.getGender();
            String address = admin.getAddress();
            String accessLevel= admin.getAccessLevel();
            String department = admin.getDepartment();
            Date hireDate = admin.getHireDate();
            String adminType= admin.getAdminType();
            
            tblModel.addRow(new Object[]{AID, lastName,gender,address,accessLevel,department,hireDate,adminType});
        } 
    }//GEN-LAST:event_btnDisplayDataActionPerformed

    private void btnFindDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindDataActionPerformed
        // TO Find Data Button option
        int AID = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Admin ID"));
        Administrator A = AfDB.findAdmin(AID);
        if (A != null) {
            txtAdminID.setText(String.valueOf(A.getAdminID()));
            txtLastName.setText(A.getLastName());
            
            // Set radio buttons
            if (A.getGender().equals("Male")) {
                rdoMale.setSelected(true);
            } else if (A.getGender().equals("Female")) {
                rdoFemale.setSelected(true);
            }
            
            txtAddress.setText(A.getAddress());
            cmbAccessLevel.setSelectedItem(A.getAccessLevel());
            cmbDepartment.setSelectedItem(A.getDepartment());
            txtHireDate.setText(A.getHireDate().toString());
            cmbAdminType.setSelectedItem(A.getAdminType());
            
            JOptionPane.showMessageDialog(rootPane, "Patient is Found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Patient is Not Found");
        }
    }//GEN-LAST:event_btnFindDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdministratorUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCmdPanel;
    private javax.swing.JButton btnAddData;
    private javax.swing.JButton btnDeleteData;
    private javax.swing.JButton btnDisplayData;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindData;
    private javax.swing.JButton btnUpdateData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbAccessLevel;
    private javax.swing.JComboBox<String> cmbAdminType;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblAdmin;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAdminID;
    private javax.swing.JTextField txtHireDate;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
