
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AdminMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminMain.class.getName());

    /**
     * Creates new form AdminMain
     */
    public AdminMain() {
        initComponents();
        showDate();
        showTime();
        setLocationRelativeTo(this);
    }
    
    //Get System date
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-YYYY");
        String dat = s.format(d);
        lblDate.setText(dat);
    }
    
    //Get System Time
    public void showTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh-mm-ss");
                String tim = s.format (d); 
                lblTime.setText(tim);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainAPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPatientRegistration = new javax.swing.JButton();
        btnDoctorRegistration = new javax.swing.JButton();
        btnScheduleAppointment = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPayment = new javax.swing.JButton();
        btnMedicalStaffRegistration = new javax.swing.JButton();
        DatePanel1 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AdminMenuBar = new javax.swing.JMenuBar();
        MHelp = new javax.swing.JMenu();
        MItemUserManual = new javax.swing.JMenuItem();
        MItemLogout = new javax.swing.JMenuItem();
        MOption = new javax.swing.JMenu();
        MItemPatientRgn = new javax.swing.JMenuItem();
        MItemDoctorRgn = new javax.swing.JMenuItem();
        MItemMedStfRgn = new javax.swing.JMenuItem();
        MItemAppointment = new javax.swing.JMenuItem();
        MItemPayment = new javax.swing.JMenuItem();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Portal");
        setResizable(false);

        mainAPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Admin Portal");

        btnPatientRegistration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPatientRegistration.setText("Patient Registration");
        btnPatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientRegistrationActionPerformed(evt);
            }
        });

        btnDoctorRegistration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDoctorRegistration.setText("Doctor Registration");
        btnDoctorRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorRegistrationActionPerformed(evt);
            }
        });

        btnScheduleAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScheduleAppointment.setText("Schedule Appointment");
        btnScheduleAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleAppointmentActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin.png"))); // NOI18N

        btnPayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPayment.setText("Payment Process");
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        btnMedicalStaffRegistration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMedicalStaffRegistration.setText("Medical Staff Registration");
        btnMedicalStaffRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalStaffRegistrationActionPerformed(evt);
            }
        });

        DatePanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime.setText("Time");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Time:");

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDate.setText("Date");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Today:");

        javax.swing.GroupLayout DatePanel1Layout = new javax.swing.GroupLayout(DatePanel1);
        DatePanel1.setLayout(DatePanel1Layout);
        DatePanel1Layout.setHorizontalGroup(
            DatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DatePanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblDate)
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DatePanel1Layout.setVerticalGroup(
            DatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatePanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(DatePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTime)
                    .addComponent(lblDate)
                    .addComponent(jLabel7))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainAPanelLayout = new javax.swing.GroupLayout(mainAPanel);
        mainAPanel.setLayout(mainAPanelLayout);
        mainAPanelLayout.setHorizontalGroup(
            mainAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAPanelLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(mainAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnScheduleAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPatientRegistration, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoctorRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedicalStaffRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
            .addGroup(mainAPanelLayout.createSequentialGroup()
                .addGroup(mainAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainAPanelLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainAPanelLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(DatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainAPanelLayout.setVerticalGroup(
            mainAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainAPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGroup(mainAPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainAPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnPatientRegistration)
                        .addGap(18, 18, 18)
                        .addComponent(btnDoctorRegistration)
                        .addGap(18, 18, 18)
                        .addComponent(btnMedicalStaffRegistration)
                        .addGap(18, 18, 18)
                        .addComponent(btnScheduleAppointment)
                        .addGap(18, 18, 18)
                        .addComponent(btnPayment)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout))
                    .addGroup(mainAPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DatePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(459, 459, 459))
        );

        MHelp.setText("Help");

        MItemUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemUserManual.setText("User Manual");
        MItemUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemUserManualActionPerformed(evt);
            }
        });
        MHelp.add(MItemUserManual);

        MItemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemLogout.setText("Logout");
        MItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemLogoutActionPerformed(evt);
            }
        });
        MHelp.add(MItemLogout);

        AdminMenuBar.add(MHelp);

        MOption.setText("Options");

        MItemPatientRgn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemPatientRgn.setText("Patient Registration");
        MItemPatientRgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemPatientRgnActionPerformed(evt);
            }
        });
        MOption.add(MItemPatientRgn);

        MItemDoctorRgn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemDoctorRgn.setText("Doctor Registration");
        MItemDoctorRgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemDoctorRgnActionPerformed(evt);
            }
        });
        MOption.add(MItemDoctorRgn);

        MItemMedStfRgn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemMedStfRgn.setText("Medical Staff Registration");
        MItemMedStfRgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemMedStfRgnActionPerformed(evt);
            }
        });
        MOption.add(MItemMedStfRgn);

        MItemAppointment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        MItemAppointment.setText("Schedule Appointment");
        MItemAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemAppointmentActionPerformed(evt);
            }
        });
        MOption.add(MItemAppointment);

        MItemPayment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemPayment.setText("Payment Process");
        MItemPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemPaymentActionPerformed(evt);
            }
        });
        MOption.add(MItemPayment);

        AdminMenuBar.add(MOption);

        setJMenuBar(AdminMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainAPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 766, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainAPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 587, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientRegistrationActionPerformed
        // TO Patient Registration Button Option
        PatientProfile ppUI=new PatientProfile();
        ppUI.setVisible(true);
    }//GEN-LAST:event_btnPatientRegistrationActionPerformed

    private void btnDoctorRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorRegistrationActionPerformed
        // TO Doctor Registration Button Option
        DoctorProfile dpUI=new DoctorProfile();
        dpUI.setVisible(true);
    }//GEN-LAST:event_btnDoctorRegistrationActionPerformed

    private void btnScheduleAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleAppointmentActionPerformed
        // TO Schedule Appointment Button Option
        AppointmentUI aUI=new AppointmentUI();
        aUI.setVisible(true);
    }//GEN-LAST:event_btnScheduleAppointmentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TO Logout Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
        // TO Payment Process Button Option
        BillUI bUI=new BillUI();
        bUI.setVisible(true);
        
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnMedicalStaffRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalStaffRegistrationActionPerformed
        // TO Medical Staff Registration Button Option
        AdministratorUI AUI=new AdministratorUI();
        AUI.setVisible(true);
    }//GEN-LAST:event_btnMedicalStaffRegistrationActionPerformed

    private void MItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemLogoutActionPerformed
        // TO Logout Menu Item Option
        this.setVisible(false);
    }//GEN-LAST:event_MItemLogoutActionPerformed

    private void MItemPatientRgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemPatientRgnActionPerformed
        // TO Patient Registration Menu Item Option
        PatientProfile ppUI=new PatientProfile();
        ppUI.setVisible(true);
    }//GEN-LAST:event_MItemPatientRgnActionPerformed

    private void MItemMedStfRgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemMedStfRgnActionPerformed
        // TO Medical Staff Registration Menu Item Option
        AdministratorUI AUI=new AdministratorUI();
        AUI.setVisible(true);
    }//GEN-LAST:event_MItemMedStfRgnActionPerformed

    private void MItemDoctorRgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemDoctorRgnActionPerformed
        // TO Doctor Registration Menu Item Option
        DoctorProfile dpUI=new DoctorProfile();
        dpUI.setVisible(true);
    }//GEN-LAST:event_MItemDoctorRgnActionPerformed

    private void MItemAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemAppointmentActionPerformed
        // TO Schedule Appointment Menu Item Option
        AppointmentUI aUI=new AppointmentUI();
        aUI.setVisible(true);
    }//GEN-LAST:event_MItemAppointmentActionPerformed

    private void MItemPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemPaymentActionPerformed
        // TO Payment Process Menu Item Option
        BillUI bUI=new BillUI();
        bUI.setVisible(true);
    }//GEN-LAST:event_MItemPaymentActionPerformed

    private void MItemUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemUserManualActionPerformed
        // TO Manu Bar User Manual Menu Item Perform
        try {
        // Path to Word document
        File manual = new File("E:/Software Engineering/Semester 2/Assignments/PR/MediCareHospital/UserManual.docx");

        if (manual.exists()) {
            Desktop.getDesktop().open(manual);
        } else {
            JOptionPane.showMessageDialog(this, "User Manual file not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Unable to open User Manual", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }    
    }//GEN-LAST:event_MItemUserManualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar AdminMenuBar;
    private javax.swing.JPanel DatePanel1;
    private javax.swing.JMenu MHelp;
    private javax.swing.JMenuItem MItemAppointment;
    private javax.swing.JMenuItem MItemDoctorRgn;
    private javax.swing.JMenuItem MItemLogout;
    private javax.swing.JMenuItem MItemMedStfRgn;
    private javax.swing.JMenuItem MItemPatientRgn;
    private javax.swing.JMenuItem MItemPayment;
    private javax.swing.JMenuItem MItemUserManual;
    private javax.swing.JMenu MOption;
    private javax.swing.JButton btnDoctorRegistration;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMedicalStaffRegistration;
    private javax.swing.JButton btnPatientRegistration;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton btnScheduleAppointment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel mainAPanel;
    // End of variables declaration//GEN-END:variables
}
