/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import Hospital.Appointment;
import java.sql.Date;
import javax.swing.JOptionPane;
import Data.AppointmentFileDB;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class AppointmentUI extends javax.swing.JFrame {
    
    private Appointment app; 
    private DefaultTableModel tblModel;
    private AppointmentFileDB afDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Appointment.class.getName());

    /**
     * Creates new form appointment
     */
    public AppointmentUI() {
        initComponents();
        setLocationRelativeTo(this);
        afDB=new AppointmentFileDB();
        tblModel=new DefaultTableModel();
        tblappointment.setModel(tblModel);
        tblModel.addColumn("Appointment ID");
        tblModel.addColumn("Patient");
        tblModel.addColumn("Doctor");
        tblModel.addColumn("Appointment Date");
        tblModel.addColumn("Appointment Time");
        tblModel.addColumn("Type");
        tblModel.addColumn("Status");
        tblModel.addColumn("Notes");
    }
    
    private boolean checkVal(){
        
        if (txtAppointmentID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Appointment ID cannot be blank");
            return false;
        }
        if (txtPatientID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Patient ID cannot be blank");
            return false;
        }
        if (txtDoctorName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Doctor Name cannot be blank");
            return false;
        }
        if (txtAppointmentDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Appointment Date cannot be blank");
            return false;
        }
        if (txtAppointmentTime.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Appointment Time cannot be blank");
            return false;
        }
        if (!rdoConfirmed.isSelected() && !rdoRescheduled.isSelected() && !rdoPending.isSelected()) {
            JOptionPane.showMessageDialog(this, "Select appointment status");
            return false;
        }
        if (txtNotes.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Notes cannot be blank");
            return false;
        }
        try{
             Date appointmentDate=Date.valueOf(txtAppointmentDate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Appointment Date must be YYYY-MM-DD");
            return false;
        }
        
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        appointmentPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnScheduleAppointment = new javax.swing.JButton();
        btnDisplayAppointment = new javax.swing.JButton();
        btnFindAppointment = new javax.swing.JButton();
        btnReschduleAppointment = new javax.swing.JButton();
        btnCancelAppointment = new javax.swing.JButton();
        btnSendReminder = new javax.swing.JButton();
        txtAppointmentID = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        rdoConfirmed = new javax.swing.JRadioButton();
        rdoRescheduled = new javax.swing.JRadioButton();
        rdoPending = new javax.swing.JRadioButton();
        txtNotes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblappointment = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appoinment");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Appointment Portal");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Appointment ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Doctor Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Appointment Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Appointment Time");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Satus");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Type");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Notes");

        appointmentPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnScheduleAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnScheduleAppointment.setText("Schedule Appointment");
        btnScheduleAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduleAppointmentActionPerformed(evt);
            }
        });

        btnDisplayAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplayAppointment.setText("Display Appointment");
        btnDisplayAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAppointmentActionPerformed(evt);
            }
        });

        btnFindAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFindAppointment.setText("Find Appointment");
        btnFindAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAppointmentActionPerformed(evt);
            }
        });

        btnReschduleAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReschduleAppointment.setText("Reschedule Appointment");
        btnReschduleAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReschduleAppointmentActionPerformed(evt);
            }
        });

        btnCancelAppointment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancelAppointment.setText("Cancel Appointment");
        btnCancelAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelAppointmentActionPerformed(evt);
            }
        });

        btnSendReminder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSendReminder.setText("Send Reminder");
        btnSendReminder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendReminderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appointmentPanelLayout = new javax.swing.GroupLayout(appointmentPanel);
        appointmentPanel.setLayout(appointmentPanelLayout);
        appointmentPanelLayout.setHorizontalGroup(
            appointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, appointmentPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(appointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSendReminder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnScheduleAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReschduleAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplayAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFindAppointment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        appointmentPanelLayout.setVerticalGroup(
            appointmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnScheduleAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDisplayAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFindAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReschduleAppointment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelAppointment)
                .addGap(9, 9, 9)
                .addComponent(btnSendReminder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        txtAppointmentID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPatientID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientIDActionPerformed(evt);
            }
        });

        txtDoctorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtAppointmentDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAppointmentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentDateActionPerformed(evt);
            }
        });

        txtAppointmentTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consultation", "Routine check-up", "Emergency", "Lab test", "Vaccination" }));

        buttonGroup1.add(rdoConfirmed);
        rdoConfirmed.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoConfirmed.setText("Confirmed");
        rdoConfirmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoConfirmedActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoRescheduled);
        rdoRescheduled.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoRescheduled.setText("Rescheduled");
        rdoRescheduled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoRescheduledActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoPending);
        rdoPending.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoPending.setText("Pending");

        txtNotes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblappointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblappointment);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rdoConfirmed)
                                                .addGap(18, 18, 18)
                                                .addComponent(rdoRescheduled))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoPending, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(57, 57, 57)
                                                    .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(175, 175, 175)))
                        .addComponent(appointmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAppointmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtAppointmentTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rdoConfirmed)
                            .addComponent(rdoRescheduled)
                            .addComponent(rdoPending))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(appointmentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void rdoRescheduledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoRescheduledActionPerformed
        // TODO scheduleAppointment your handling code here:
    }//GEN-LAST:event_rdoRescheduledActionPerformed

    private void txtAppointmentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentDateActionPerformed
        // TODO scheduleAppointment your handling code here:
    }//GEN-LAST:event_txtAppointmentDateActionPerformed

    private void txtPatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientIDActionPerformed
        // TODO scheduleAppointment your handling code here:
    }//GEN-LAST:event_txtPatientIDActionPerformed

    private void btnScheduleAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduleAppointmentActionPerformed
        // TO Schedule Appointment Button Option
        if (checkVal()){
            int appointmentID = Integer.valueOf(txtAppointmentID.getText());
            String patient = txtPatientID.getText();
            String doctor = txtDoctorName.getText();
            Date appointmentDate=Date.valueOf(txtAppointmentDate.getText());
            String appointmentTime=txtAppointmentTime.getText();
            
            String type = cmbType.getSelectedItem().toString();

            String status="";
            if(rdoConfirmed.isSelected()) {
                status="Confirmed";
            } else if (rdoRescheduled.isSelected()){
                status="Rescheduled";
            } else if (rdoPending.isSelected()){
                status="Pending";
            } else {
                status="";
            }
            
            String notes=txtNotes.getText();

            app = new Appointment (appointmentID, patient, doctor, appointmentDate, appointmentTime, type, status, notes);
            if (afDB.scheduleAppointment(app))           
              JOptionPane.showMessageDialog(rootPane, "The Appointment Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "The Appointment Record is not added");
        }
    }//GEN-LAST:event_btnScheduleAppointmentActionPerformed

    private void btnDisplayAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAppointmentActionPerformed
        // TO Display Appointment Button Option
        ArrayList<Appointment> aList=afDB.getAll();
        tblModel.setRowCount(0);
        for(Appointment app:aList){
            int aID= app.getAppointmentID();
            String patient= app.getPatient();
            String doctor = app.getDoctor();
            Date appointmentDate = app.getAppointmentDate();
            String appointmentTime = app.getAppointmentTime();
            String type = app.getType();
            String status = app.getStatus();
            String notes = app.getNotes();
            tblModel.addRow(new Object[]{aID,patient,doctor,appointmentDate,appointmentTime,type,status,notes});
        } 
    }//GEN-LAST:event_btnDisplayAppointmentActionPerformed

    private void btnFindAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAppointmentActionPerformed
        // TO Find Appointment Button Option
        int aID = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Appointment ID"));
        Appointment a = afDB.findAppointment(aID);
        if (a != null) {
            txtAppointmentID.setText(String.valueOf(a.getAppointmentID()));
            txtPatientID.setText(a.getPatient());
            txtDoctorName.setText(a.getDoctor());
            txtAppointmentDate.setText(a.getAppointmentDate().toString());
            txtAppointmentTime.setText(a.getAppointmentTime());
            cmbType.setSelectedItem(a.getType());
            txtNotes.setText(a.getNotes());

            // Set radio buttons
            if (a.getStatus().equals("Confirmed")) {
                rdoConfirmed.setSelected(true);
            } else if (a.getStatus().equals("Rescheduled")) {
                rdoRescheduled.setSelected(true);
            } else if (a.getStatus().equals("Pending")) {
                rdoPending.setSelected(true);
            }

            JOptionPane.showMessageDialog(rootPane, "Appointment is Found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Appointment is Not Found");
        }
    }//GEN-LAST:event_btnFindAppointmentActionPerformed

    private void btnReschduleAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReschduleAppointmentActionPerformed
        // TO Reschdule Appointment Button Option
        if (checkVal()){
            int appointmentID = Integer.valueOf(txtAppointmentID.getText());
            String patient = txtPatientID.getText();
            String doctor = txtDoctorName.getText();
            Date appointmentDate=Date.valueOf(txtAppointmentDate.getText());
            String appointmentTime=txtAppointmentTime.getText();
            
            String type = cmbType.getSelectedItem().toString();

            String status="";
            if(rdoConfirmed.isSelected()) {
                status="Confirmed";
            } else if (rdoRescheduled.isSelected()){
                status="Rescheduled";
            } else if (rdoPending.isSelected()){
                status="Pending";
            } else {
                status="";
            }
            
            String notes=txtNotes.getText();

            app = new Appointment (appointmentID, patient, doctor, appointmentDate, appointmentTime, type, status, notes);
            if (afDB.rescheduleAppointment(app))           
              JOptionPane.showMessageDialog(rootPane, "The Appointment Record is updated");
            else
               JOptionPane.showMessageDialog(rootPane, "The Appointment Record is not updated");
        }
    }//GEN-LAST:event_btnReschduleAppointmentActionPerformed

    private void btnCancelAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelAppointmentActionPerformed
        // TO Cancel Appointment Button Option
        int aID=Integer.valueOf(JOptionPane.showInputDialog("Enter Appoinment ID"));
        if(afDB.cancelAppointment(aID))
            JOptionPane.showMessageDialog(rootPane, "Record is deleted");
        else
             JOptionPane.showMessageDialog(rootPane, "Record is not deleted");
    }//GEN-LAST:event_btnCancelAppointmentActionPerformed

    private void rdoConfirmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoConfirmedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoConfirmedActionPerformed

    private void btnSendReminderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendReminderActionPerformed
        // TO Send Reminder Button Option
        try {
        int aID = Integer.parseInt(
                JOptionPane.showInputDialog(this, "Enter Appointment ID to send reminder")
        );

        Appointment a = afDB.findAppointment(aID);

        if (a != null) {
            String message =
                    "** Appointment Reminder **\n\n" +
                    "Appointment ID: " + a.getAppointmentID() + "\n" +
                    "Patient: " + a.getPatient() + "\n" +
                    "Doctor: " + a.getDoctor() + "\n" +
                    "Date: " + a.getAppointmentDate() + "\n" +
                    "Time: " + a.getAppointmentTime() + "\n" +
                    "Status: " + a.getStatus()+ "\n" +
                    "Notes: " + a.getNotes();

            JOptionPane.showMessageDialog(
                    this,
                    message,
                    "Reminder Sent",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(this, "Appointment not found");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Invalid Appointment ID");
      }
    }//GEN-LAST:event_btnSendReminderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Appointment().setVisible(true));
        java.awt.EventQueue.invokeLater(() -> new AppointmentUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointmentPanel;
    private javax.swing.JButton btnCancelAppointment;
    private javax.swing.JButton btnDisplayAppointment;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindAppointment;
    private javax.swing.JButton btnReschduleAppointment;
    private javax.swing.JButton btnScheduleAppointment;
    private javax.swing.JButton btnSendReminder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoConfirmed;
    private javax.swing.JRadioButton rdoPending;
    private javax.swing.JRadioButton rdoRescheduled;
    private javax.swing.JTable tblappointment;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentID;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtPatientID;
    // End of variables declaration//GEN-END:variables
}
