/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Hospital.Bill;
import java.sql.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class BillUI extends javax.swing.JFrame {
    
    private Bill bill; 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillUI.class.getName());

    /**
     * Creates new form Bill
     */
    public BillUI() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    private boolean checkVal(){
        
        if (txtBillID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Bill ID cannot be blank");
            return false;
        }
        if (txtPatient.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Patient ID cannot be blank");
            return false;
        }
        if (txtInsuranceCoverage.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Insurance Coverage cannot be blank");
            return false;
        }
        if (txtDueDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Due Date cannot be blank");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTotal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoCards = new javax.swing.JRadioButton();
        rdoTransfer = new javax.swing.JRadioButton();
        rdoMoibile = new javax.swing.JRadioButton();
        paymentCmdPanel = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtBillID = new javax.swing.JTextField();
        txtPatient = new javax.swing.JTextField();
        txtDueDate = new javax.swing.JTextField();
        cmbConFee = new javax.swing.JComboBox<>();
        txtInsuranceCoverage = new javax.swing.JTextField();
        ckbRoomCharges = new javax.swing.JCheckBox();
        ckbSurgeryService = new javax.swing.JCheckBox();
        ckbPhysiotherapy = new javax.swing.JCheckBox();
        ckbEmergency = new javax.swing.JCheckBox();
        ckbNursing = new javax.swing.JCheckBox();
        ckbTablets = new javax.swing.JCheckBox();
        ckbSyrups = new javax.swing.JCheckBox();
        ckbInjections = new javax.swing.JCheckBox();
        ckbAntibiotics = new javax.swing.JCheckBox();
        ckbBlood = new javax.swing.JCheckBox();
        ckbXRay = new javax.swing.JCheckBox();
        ckbMRI = new javax.swing.JCheckBox();
        ckbCT = new javax.swing.JCheckBox();
        txtTotal = new javax.swing.JTextField();
        ckbPainkillers = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment Process");
        setResizable(false);

        lblTotal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Payment Process");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Bill ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Services");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Madications");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Consultation Fees");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Test Charges");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Total Amount");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Payment Status");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Insurance Coverage");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Due Date");

        rdoCash.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoCash.setText("Cash");

        rdoCards.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoCards.setText("Cards (Debit/Credit)");
        rdoCards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCardsActionPerformed(evt);
            }
        });

        rdoTransfer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoTransfer.setText("Bank Transfers");

        rdoMoibile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoMoibile.setText("Mobile Wallets");

        paymentCmdPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Generate Bill");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentCmdPanelLayout = new javax.swing.GroupLayout(paymentCmdPanel);
        paymentCmdPanel.setLayout(paymentCmdPanelLayout);
        paymentCmdPanelLayout.setHorizontalGroup(
            paymentCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentCmdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paymentCmdPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
        );
        paymentCmdPanelLayout.setVerticalGroup(
            paymentCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentCmdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(27, 27, 27)
                .addComponent(btnPrint)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        txtBillID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPatient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDueDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbConFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbConFee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor Consultation-$10", "Specialist Consultation-$15" }));

        txtInsuranceCoverage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ckbRoomCharges.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbRoomCharges.setText("Room Charges - $20");

        ckbSurgeryService.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbSurgeryService.setText("Surgery Services - $15");

        ckbPhysiotherapy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbPhysiotherapy.setText("Physiotherapy - $10");

        ckbEmergency.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbEmergency.setText("Emergency Services - $7");

        ckbNursing.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbNursing.setText("Nursing Services - $10");
        ckbNursing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNursingActionPerformed(evt);
            }
        });

        ckbTablets.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbTablets.setText("Tablets -$5");

        ckbSyrups.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbSyrups.setText("Syrups -$7");

        ckbInjections.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbInjections.setText("Injections - $10");

        ckbAntibiotics.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbAntibiotics.setText("Antibiotics - $5");

        ckbBlood.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbBlood.setText("Blood Test - $5");
        ckbBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbBloodActionPerformed(evt);
            }
        });

        ckbXRay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbXRay.setText("X-Ray - $7");

        ckbMRI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbMRI.setText("MRI - $20");

        ckbCT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbCT.setText("CT Scan - $30");

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotal.setText("Please leave this field empty");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        ckbPainkillers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ckbPainkillers.setText("Painkillers - $3");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lblTotalLayout = new javax.swing.GroupLayout(lblTotal);
        lblTotal.setLayout(lblTotalLayout);
        lblTotalLayout.setHorizontalGroup(
            lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTotalLayout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(lblTotalLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblTotalLayout.createSequentialGroup()
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7))
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblTotalLayout.createSequentialGroup()
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbBlood)
                                    .addComponent(ckbTablets))
                                .addGap(18, 18, 18)
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbXRay)
                                    .addComponent(ckbSyrups))
                                .addGap(18, 18, 18)
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbInjections)
                                    .addComponent(ckbMRI))
                                .addGap(18, 18, 18)
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbCT)
                                    .addGroup(lblTotalLayout.createSequentialGroup()
                                        .addComponent(ckbAntibiotics)
                                        .addGap(26, 26, 26)
                                        .addComponent(ckbPainkillers))))
                            .addComponent(cmbConFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(lblTotalLayout.createSequentialGroup()
                                .addComponent(rdoCash)
                                .addGap(27, 27, 27)
                                .addComponent(rdoCards)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoMoibile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoTransfer))
                            .addGroup(lblTotalLayout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(lblTotalLayout.createSequentialGroup()
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(62, 62, 62)
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblTotalLayout.createSequentialGroup()
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(lblTotalLayout.createSequentialGroup()
                                        .addComponent(txtBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3))
                                    .addGroup(lblTotalLayout.createSequentialGroup()
                                        .addComponent(ckbRoomCharges)
                                        .addGap(54, 54, 54)
                                        .addComponent(ckbSurgeryService)))
                                .addGap(30, 30, 30)
                                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ckbPhysiotherapy)
                                    .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(lblTotalLayout.createSequentialGroup()
                                .addComponent(ckbEmergency)
                                .addGap(18, 18, 18)
                                .addComponent(ckbNursing)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(paymentCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        lblTotalLayout.setVerticalGroup(
            lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTotalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblTotalLayout.createSequentialGroup()
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtBillID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ckbRoomCharges)
                            .addComponent(ckbSurgeryService)
                            .addComponent(ckbPhysiotherapy))
                        .addGap(18, 18, 18)
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbEmergency)
                            .addComponent(ckbNursing))
                        .addGap(18, 18, 18)
                        .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbConFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(paymentCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbTablets)
                    .addComponent(ckbSyrups)
                    .addComponent(ckbInjections)
                    .addComponent(ckbAntibiotics)
                    .addComponent(ckbPainkillers)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ckbBlood)
                    .addComponent(ckbXRay)
                    .addComponent(ckbMRI)
                    .addComponent(ckbCT))
                .addGap(18, 18, 18)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtInsuranceCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(lblTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdoCash)
                    .addComponent(rdoCards)
                    .addComponent(rdoMoibile)
                    .addComponent(rdoTransfer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoCardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCardsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoCardsActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // To Cancel Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TO Add Button Option
        if (!checkVal()) return; // stop if validation fails

        try {
            int billID = Integer.parseInt(txtBillID.getText());
            String patient = txtPatient.getText();

            //Services
            double totService = 0.0;
                if (ckbRoomCharges.isSelected()) totService += 20.0;
                if (ckbSurgeryService.isSelected()) totService += 15.0;
                if (ckbPhysiotherapy.isSelected()) totService += 10.0;
                if (ckbEmergency.isSelected()) totService += 7.0;
                if (ckbNursing.isSelected()) totService += 10.0;

            //Consultation Fees
            double totConFees = 0.0;
                if (cmbConFee.getSelectedIndex() == 0) totConFees = 10.0;
                else totConFees = 15.0;

            //Medications
            double totMedications = 0.0;
                if (ckbTablets.isSelected()) totMedications += 5.0;
                if (ckbSyrups.isSelected()) totMedications += 7.0;
                if (ckbInjections.isSelected()) totMedications += 10.0;
                if (ckbAntibiotics.isSelected()) totMedications += 5.0;
                if (ckbPainkillers.isSelected()) totMedications += 3.0;

            //Test Charges 
            double totTestchgs = 0.0;
                if (ckbBlood.isSelected()) totTestchgs += 5.0;
                if (ckbXRay.isSelected()) totTestchgs += 7.0;
                if (ckbMRI.isSelected()) totTestchgs += 20.0;
                if (ckbCT.isSelected()) totTestchgs += 30.0;

            //Insurance Coverage
            double insurance = Double.parseDouble(txtInsuranceCoverage.getText());

            //Total Amount
            double totalAmount = totService + totConFees + totMedications + totTestchgs - insurance;
            txtTotal.setText(String.valueOf(totalAmount));

            /*double totalAmount = totService + totConFees + totMedications + totTestchgs - insurance;
            txtTotal.setText(String.format("%.2f", totalAmount));*/

            
            
            //Payment Status
            String paymentStatus = "";
                if (rdoCash.isSelected()) paymentStatus = "Cash";
                else if (rdoCards.isSelected()) paymentStatus = "Cards";
                else if (rdoMoibile.isSelected()) paymentStatus = "Mobile Wallet";
                else if (rdoTransfer.isSelected()) paymentStatus = "Bank Transfer";

            //Due Date
            Date dueDate = Date.valueOf(txtDueDate.getText()); // yyyy-mm-dd

            //Selected Services description
            StringBuilder servicesDesc = new StringBuilder();
                if (ckbRoomCharges.isSelected()) servicesDesc.append("Room $20, ");
                if (ckbSurgeryService.isSelected()) servicesDesc.append("Surgery $15, ");
                if (ckbPhysiotherapy.isSelected()) servicesDesc.append("Physiotherapy $10, ");
                if (ckbEmergency.isSelected()) servicesDesc.append("Emergency $7, ");
                if (ckbNursing.isSelected()) servicesDesc.append("Nursing $10, ");
            String servicesString = servicesDesc.toString();
                if (!servicesString.isEmpty()) servicesString = servicesString.substring(0, servicesString.length()-2);

            //Create Bill object
            bill = new Bill(billID, patient, servicesString, totMedications, totConFees, totTestchgs, totalAmount, paymentStatus, insurance, dueDate);

            JOptionPane.showMessageDialog(paymentCmdPanel, "Bill generated successfully! You can now print the receipt.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for Bill ID and Insurance Coverage.");
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Please enter Due Date in yyyy-mm-dd format.");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void ckbNursingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNursingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbNursingActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TO Print Button Option
        if (bill == null) {
        JOptionPane.showMessageDialog(this, "No bill available. Please generate a bill first.");
        return;
        }

        StringBuilder receipt = new StringBuilder();
        receipt.append("<html><b> ========== Hospital Bill ========== </b></html>\n\n");
        receipt.append("Bill ID: ").append(bill.getBillID()).append("\n");
        receipt.append("Patient Name: ").append(bill.getPatient()).append("\n");
        receipt.append("Services: ").append(bill.getServices()).append("\n\n");

        receipt.append("Charges:\n");
        receipt.append("  Medications: $").append(bill.getMadications()).append("\n");
        receipt.append("  Consultation Fees: $").append(bill.getConsultationFees()).append("\n");
        receipt.append("  Test Charges: $").append(bill.getTestCharges()).append("\n\n");

        receipt.append("Insurance Coverage: $").append(bill.getInsuranceCoverage()).append("\n\n");
        receipt.append("Total Amount: $").append(bill.getTotalAmount()).append("\n\n");
        receipt.append("Payment Method: ").append(bill.getPaymentStatus()).append("\n");
        receipt.append("Due Date: ").append(bill.getDueDate()).append("\n\n");
        receipt.append("==================================");

        JOptionPane.showMessageDialog(paymentCmdPanel, receipt.toString(), "Receipt", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void ckbBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbBloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbBloodActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckbAntibiotics;
    private javax.swing.JCheckBox ckbBlood;
    private javax.swing.JCheckBox ckbCT;
    private javax.swing.JCheckBox ckbEmergency;
    private javax.swing.JCheckBox ckbInjections;
    private javax.swing.JCheckBox ckbMRI;
    private javax.swing.JCheckBox ckbNursing;
    private javax.swing.JCheckBox ckbPainkillers;
    private javax.swing.JCheckBox ckbPhysiotherapy;
    private javax.swing.JCheckBox ckbRoomCharges;
    private javax.swing.JCheckBox ckbSurgeryService;
    private javax.swing.JCheckBox ckbSyrups;
    private javax.swing.JCheckBox ckbTablets;
    private javax.swing.JCheckBox ckbXRay;
    private javax.swing.JComboBox<String> cmbConFee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lblTotal;
    private javax.swing.JPanel paymentCmdPanel;
    private javax.swing.JRadioButton rdoCards;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMoibile;
    private javax.swing.JRadioButton rdoTransfer;
    private javax.swing.JTextField txtBillID;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtInsuranceCoverage;
    private javax.swing.JTextField txtPatient;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
