/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Hospital.Doctor;
import Hospital.MedicalStaff;
import Hospital.Person;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Data.DoctorFileDB;

/**
 *
 * @author USER
 */
public class DoctorProfile extends javax.swing.JFrame {
    
    private Doctor Doc; 
    private DefaultTableModel tblModel;
    private DoctorFileDB dfDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorProfile.class.getName());

    /**
     * Creates new form DoctorProfile
     */
    public DoctorProfile() {
        initComponents();
        setLocationRelativeTo(this);
        dfDB=new DoctorFileDB();
        tblModel=new DefaultTableModel();
        tblDoctor.setModel(tblModel);
        tblModel.addColumn("Staff ID");
        tblModel.addColumn("Specialization");
        tblModel.addColumn("Consultation Fee");
        tblModel.addColumn("License Number");
        tblModel.addColumn("Years Of Experience");
        tblModel.addColumn("Salary");
    }

    //To check each fields are not blank
    private boolean checkVal(){
        
        if (txtSaffID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Staff ID cannot be blank");
            return false;
        }
        if (txtLicenseNo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "License Number cannot be blank");
            return false;
        }
         if (txtSalary.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Salary cannot be blank");
            return false;
        }   
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DoctorPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnAddDoctor = new javax.swing.JButton();
        btnDisplayDoctorInfo = new javax.swing.JButton();
        btnDeleteDoctorProfile = new javax.swing.JButton();
        btnFinddoctor = new javax.swing.JButton();
        btnUpdateDoctorInfo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLicenseNo = new javax.swing.JTextField();
        cmbYearsOfExp = new javax.swing.JComboBox<>();
        cmbFee = new javax.swing.JComboBox<>();
        cmbSpecialization = new javax.swing.JComboBox<>();
        txtSaffID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor Profile");
        setResizable(false);

        DoctorPanel.setBackground(new java.awt.Color(255, 255, 255));
        DoctorPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Create Doctor Profile");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAddDoctor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAddDoctor.setText("Add Doctor Info");
        btnAddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDoctorActionPerformed(evt);
            }
        });

        btnDisplayDoctorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplayDoctorInfo.setText("Display Doctor Info");
        btnDisplayDoctorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayDoctorInfoActionPerformed(evt);
            }
        });

        btnDeleteDoctorProfile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeleteDoctorProfile.setText("Delete Doctor Profile");
        btnDeleteDoctorProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDoctorProfileActionPerformed(evt);
            }
        });

        btnFinddoctor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFinddoctor.setText("Find Doctor Info");
        btnFinddoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinddoctorActionPerformed(evt);
            }
        });

        btnUpdateDoctorInfo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdateDoctorInfo.setText("Update Doctor Info");
        btnUpdateDoctorInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDoctorInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnExit)
                .addGap(76, 76, 76)
                .addComponent(btnAddDoctor)
                .addGap(72, 72, 72)
                .addComponent(btnDisplayDoctorInfo)
                .addGap(81, 81, 81)
                .addComponent(btnFinddoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btnUpdateDoctorInfo)
                .addGap(84, 84, 84)
                .addComponent(btnDeleteDoctorProfile)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnAddDoctor)
                    .addComponent(btnDisplayDoctorInfo)
                    .addComponent(btnDeleteDoctorProfile)
                    .addComponent(btnFinddoctor)
                    .addComponent(btnUpdateDoctorInfo))
                .addGap(32, 32, 32))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Years Of Experience");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Consultation Fee");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("License Number");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Specialization");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Staff ID");

        txtLicenseNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbYearsOfExp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbYearsOfExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10", "Above 10" }));

        cmbFee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbFee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2500", "3000", "3500", "4000" }));

        cmbSpecialization.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbSpecialization.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Physician", "Pediatrician", "Cardiologist", "Dermatologist", "Orthopedic Surgeon", "Gynecologist" }));

        txtSaffID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDoctor);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Salary");

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout DoctorPanelLayout = new javax.swing.GroupLayout(DoctorPanel);
        DoctorPanel.setLayout(DoctorPanelLayout);
        DoctorPanelLayout.setHorizontalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DoctorPanelLayout.createSequentialGroup()
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSpecialization, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSaffID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DoctorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(cmbYearsOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DoctorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DoctorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbFee, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorPanelLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DoctorPanelLayout.createSequentialGroup()
                .addGap(494, 494, 494)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DoctorPanelLayout.setVerticalGroup(
            DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoctorPanelLayout.createSequentialGroup()
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtSaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cmbYearsOfExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDoctorActionPerformed
        // TO Add Doctor Button Option
        if (checkVal()){
            int staffID = Integer.valueOf(txtSaffID.getText());
            String specialization = cmbSpecialization.getSelectedItem().toString();
            String consultationFee = cmbFee.getSelectedItem().toString();
            String licenseNumber = txtLicenseNo.getText();
            String yearsOfExperience = cmbYearsOfExp.getSelectedItem().toString();
            String salary = txtSalary.getText();
            
            Doctor Doc = new Doctor (staffID, specialization, consultationFee, licenseNumber, yearsOfExperience, salary);
            if (dfDB.addDoctor(Doc))           
              JOptionPane.showMessageDialog(rootPane, "The Doctor Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "The Doctor Record is not added");
        }
    }//GEN-LAST:event_btnAddDoctorActionPerformed

    private void btnDisplayDoctorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayDoctorInfoActionPerformed
        // TO Display Doctor Info Button option
        ArrayList<Doctor> dList=dfDB.getAll();
        tblModel.setRowCount(0);
        for(Doctor app:dList){
            int dID= app.getStaffID();
            String specialization= app.getSpecialization();
            String consultationFee = app.getConsultationFee();
            String licenseNumber = app.getLicenseNumber();
            String yearsOfExperience = app.getYearsOfExperience();
            String salary = app.getSalary();
            tblModel.addRow(new Object[]{dID, specialization, consultationFee, licenseNumber, yearsOfExperience, salary});
        } 
    }//GEN-LAST:event_btnDisplayDoctorInfoActionPerformed

    private void btnFinddoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinddoctorActionPerformed
        // TODO add your handling code here:
        int dID = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Staff ID"));
        Doctor d = dfDB.findDoctor(dID);
        if (d != null) {
            txtSaffID.setText(String.valueOf(d.getStaffID()));
            cmbSpecialization.setSelectedItem(d.getSpecialization());
            cmbFee.setSelectedItem(d.getConsultationFee());
            txtLicenseNo.setText(d.getLicenseNumber());
            cmbYearsOfExp.setSelectedItem(d.getYearsOfExperience());
            txtSalary.setText(d.getSalary());

            JOptionPane.showMessageDialog(rootPane, "Doctor Record is Found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Doctor Record Not Found");
        }
    }//GEN-LAST:event_btnFinddoctorActionPerformed

    private void btnUpdateDoctorInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDoctorInfoActionPerformed
        // TODO add your handling code here:
        if (checkVal()){
            int staffID = Integer.valueOf(txtSaffID.getText());
            String specialization = cmbSpecialization.getSelectedItem().toString();
            String consultationFee = cmbFee.getSelectedItem().toString();
            String licenseNumber = txtLicenseNo.getText();
            String yearsOfExperience = cmbYearsOfExp.getSelectedItem().toString();
            String salary=txtSalary.getText();

            Doc = new Doctor (staffID, specialization, consultationFee, licenseNumber, yearsOfExperience, salary);
            if (dfDB.updateDoctor(Doc))           
              JOptionPane.showMessageDialog(rootPane, "Doctor Record is updated");
            else
               JOptionPane.showMessageDialog(rootPane, "Doctor Record is not updated");
        }
    }//GEN-LAST:event_btnUpdateDoctorInfoActionPerformed

    private void btnDeleteDoctorProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDoctorProfileActionPerformed
        // TODO add your handling code here:
        int dID=Integer.valueOf(JOptionPane.showInputDialog("Enter Staff ID"));
        if(dfDB.deleteDoctor(dID))
            JOptionPane.showMessageDialog(rootPane, "Record is deleted");
        else
             JOptionPane.showMessageDialog(rootPane, "Record is not deleted");
    }//GEN-LAST:event_btnDeleteDoctorProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DoctorProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorPanel;
    private javax.swing.JButton btnAddDoctor;
    private javax.swing.JButton btnDeleteDoctorProfile;
    private javax.swing.JButton btnDisplayDoctorInfo;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFinddoctor;
    private javax.swing.JButton btnUpdateDoctorInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbFee;
    private javax.swing.JComboBox<String> cmbSpecialization;
    private javax.swing.JComboBox<String> cmbYearsOfExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTextField txtLicenseNo;
    private javax.swing.JTextField txtSaffID;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
