/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Data.LabFileDB;
import Hospital.Lab;
import javax.swing.JTable;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class LabUI extends javax.swing.JFrame {
    
    private Lab lab; 
    private DefaultTableModel tblModel;
    private LabFileDB LfDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LabUI.class.getName());

    /**
     * Creates new form LabUI
     */
    public LabUI() {
        initComponents();
        setLocationRelativeTo(this);
        LfDB=new LabFileDB();
        tblModel=new DefaultTableModel();
        tblLabRecord.setModel(tblModel);
        tblModel.addColumn("Test No");
        tblModel.addColumn("Test");
        tblModel.addColumn("Test Result");
    }
    
    private boolean checkVal(){
        
        if (txtTestNo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Test No cannot be blank");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labRecordPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTestNo = new javax.swing.JTextField();
        cmbTestResult = new javax.swing.JComboBox<>();
        rdoBloodTest = new javax.swing.JRadioButton();
        rdoXRay = new javax.swing.JRadioButton();
        rdoMRI = new javax.swing.JRadioButton();
        rdoCTScan = new javax.swing.JRadioButton();
        labRecordCmdPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabRecord = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab Tech");
        setResizable(false);

        labRecordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lab Records");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Test No");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Test");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Test Results");

        txtTestNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbTestResult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbTestResult.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Progress", "Pending", "Completed" }));

        rdoBloodTest.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoBloodTest.setText("Blood Test");
        rdoBloodTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBloodTestActionPerformed(evt);
            }
        });

        rdoXRay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoXRay.setText("X-Ray");

        rdoMRI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoMRI.setText("MRI");

        rdoCTScan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoCTScan.setText("CT Scan");

        labRecordCmdPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labRecordCmdPanelLayout = new javax.swing.GroupLayout(labRecordCmdPanel);
        labRecordCmdPanel.setLayout(labRecordCmdPanelLayout);
        labRecordCmdPanelLayout.setHorizontalGroup(
            labRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labRecordCmdPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnAdd)
                .addGap(137, 137, 137)
                .addComponent(btnDisplay)
                .addGap(62, 62, 62))
        );
        labRecordCmdPanelLayout.setVerticalGroup(
            labRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labRecordCmdPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(labRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDisplay)
                    .addComponent(btnExit))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tblLabRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLabRecord);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout labRecordPanelLayout = new javax.swing.GroupLayout(labRecordPanel);
        labRecordPanel.setLayout(labRecordPanelLayout);
        labRecordPanelLayout.setHorizontalGroup(
            labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labRecordPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTestNo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoBloodTest)
                    .addGroup(labRecordPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoXRay, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoMRI, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoCTScan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(labRecordPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRecordCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        labRecordPanelLayout.setVerticalGroup(
            labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labRecordPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTestNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdoBloodTest)
                    .addComponent(rdoXRay)
                    .addComponent(rdoMRI)
                    .addComponent(rdoCTScan))
                .addGap(44, 44, 44)
                .addGroup(labRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labRecordCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labRecordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoBloodTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBloodTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoBloodTestActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TO Add Button Option
        if (checkVal()){
            int testNo = Integer.valueOf(txtTestNo.getText());
            
            String test="";
            if(rdoBloodTest.isSelected()) {
                test="Blood Test";
            } else if (rdoXRay.isSelected()){
                test="X-Ray";
            } else if (rdoMRI.isSelected()){
                test="MRI";
            }else if (rdoCTScan.isSelected()){
                test="CT Scan";
            } else {
                test="";
            }
            
            String testResult = cmbTestResult.getSelectedItem().toString();

            lab = new Lab (testNo, test, testResult);
            if (LfDB.addTest(lab))           
              JOptionPane.showMessageDialog(rootPane, "The Lab Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "The Lab Record is not added");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TO Display Button option
        ArrayList<Lab> LList=LfDB.Display();
        tblModel.setRowCount(0);
        for(Lab lab:LList){
            int LID= lab.getTestNo();
            String test = lab.getTest();
            String testResult = lab.getTestResult();
            
            tblModel.addRow(new Object[]{LID, test, testResult});
        } 
    }//GEN-LAST:event_btnDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LabUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbTestResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel labRecordCmdPanel;
    private javax.swing.JPanel labRecordPanel;
    private javax.swing.JRadioButton rdoBloodTest;
    private javax.swing.JRadioButton rdoCTScan;
    private javax.swing.JRadioButton rdoMRI;
    private javax.swing.JRadioButton rdoXRay;
    private javax.swing.JTable tblLabRecord;
    private javax.swing.JTextField txtTestNo;
    // End of variables declaration//GEN-END:variables
}
