/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class MainUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainUI.class.getName());

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setLocationRelativeTo(this);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        mainUIPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMovingText = new javax.swing.JLabel();
        btnDoctor = new javax.swing.JButton();
        btnNurse = new javax.swing.JButton();
        btnLabTech = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MItemUserManual = new javax.swing.JMenuItem();
        MItemClose = new javax.swing.JMenuItem();
        LoginMenu = new javax.swing.JMenu();
        MItemD = new javax.swing.JMenuItem();
        MItemN = new javax.swing.JMenuItem();
        MItemL = new javax.swing.JMenuItem();
        MItemA = new javax.swing.JMenuItem();
        MMore = new javax.swing.JMenu();
        MItemAboutUs = new javax.swing.JMenuItem();
        MItemContactUs = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MediCare Hospital");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                WindowOpened(evt);
            }
        });

        mainUIPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Welcome to Hospital Management System");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Hosoital.png"))); // NOI18N

        lblMovingText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMovingText.setText("MediCare Hospital");

        btnDoctor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnNurse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNurse.setText("Nurse");
        btnNurse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseActionPerformed(evt);
            }
        });

        btnLabTech.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLabTech.setText("Lab Technician");
        btnLabTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabTechActionPerformed(evt);
            }
        });

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAdmin.setText("Administrator");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainUIPanelLayout = new javax.swing.GroupLayout(mainUIPanel);
        mainUIPanel.setLayout(mainUIPanelLayout);
        mainUIPanelLayout.setHorizontalGroup(
            mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainUIPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNurse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLabTech, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 136, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUIPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUIPanelLayout.createSequentialGroup()
                        .addComponent(lblMovingText, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUIPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUIPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 198, 198))))
        );
        mainUIPanelLayout.setVerticalGroup(
            mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainUIPanelLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(lblMovingText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoctor)
                    .addComponent(btnLabTech))
                .addGap(38, 38, 38)
                .addGroup(mainUIPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNurse)
                    .addComponent(btnAdmin))
                .addGap(47, 47, 47)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));

        jMenu1.setText("Help");

        MItemUserManual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemUserManual.setText("User Manual ");
        MItemUserManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemUserManualActionPerformed(evt);
            }
        });
        jMenu1.add(MItemUserManual);

        MItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemClose.setText("Close");
        MItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(MItemClose);

        jMenuBar1.add(jMenu1);

        LoginMenu.setText("Login");

        MItemD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemD.setText("Doctor");
        MItemD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemDActionPerformed(evt);
            }
        });
        LoginMenu.add(MItemD);

        MItemN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemN.setText("Nurse");
        MItemN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemNActionPerformed(evt);
            }
        });
        LoginMenu.add(MItemN);

        MItemL.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemL.setText("Lab Tech");
        MItemL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemLActionPerformed(evt);
            }
        });
        LoginMenu.add(MItemL);

        MItemA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MItemA.setText("Admin");
        MItemA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemAActionPerformed(evt);
            }
        });
        LoginMenu.add(MItemA);

        jMenuBar1.add(LoginMenu);

        MMore.setText("More");

        MItemAboutUs.setText("About Us");
        MItemAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemAboutUsActionPerformed(evt);
            }
        });
        MMore.add(MItemAboutUs);

        MItemContactUs.setText("Contact Us");
        MItemContactUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MItemContactUsActionPerformed(evt);
            }
        });
        MMore.add(MItemContactUs);

        jMenuBar1.add(MMore);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainUIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // Click Doctor button and go to Doctor Login Portal
        LoginDoctor dLog= new LoginDoctor();
        dLog.setVisible(true);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnLabTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabTechActionPerformed
        // Click Lab Technician button and go to Lab Technician Login Portal
        LoginLabTechnician lLog= new LoginLabTechnician();
        lLog.setVisible(true);
    }//GEN-LAST:event_btnLabTechActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // Click Administrator button and go to Administrator Login Portal
        LoginAdmin aLog= new LoginAdmin();
        aLog.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void MItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MItemCloseActionPerformed
    
    //Automatically run the code when user open the sytem
    private void WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowOpened
        // TO Move MediCare Hospital Label
        
        //cannot be changed
        final int Max_X = 400;
        final int Min_X = 50;

        //To continuously run then label 
        Thread animation = new Thread(new Runnable() {
            @Override
            public void run() {
                int x = 20;
                int y = 30;  //label start positions
                boolean Check = true;
                
                //infinite loop
                while (true) {
                    if (Check) {
                        lblMovingText.setLocation(x, y);
                        x += 10;
                    } else {
                        lblMovingText.setLocation(x, y);
                        x -= 10;
                    }
                    if(x>Max_X){
                        Check=false;
                        x=400; //reset the X value
                    }
                    if(x<Min_X){
                        Check= true;
                    }
                    try {
                        Thread.sleep(200);
                    } catch (Exception e) {

                    }
                }
            }
        });
        animation.start();
    }//GEN-LAST:event_WindowOpened

    private void btnNurseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseActionPerformed
        // Click Nurse button and go to Nurse Login Portal
        LoginNurse nLog = new LoginNurse();
        nLog.setVisible(true);
    }//GEN-LAST:event_btnNurseActionPerformed

    private void MItemLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemLActionPerformed
        // TO Manu Bar Lab Technician Menu Item Perform
        LoginLabTechnician lLog= new LoginLabTechnician();
        lLog.setVisible(true);
    }//GEN-LAST:event_MItemLActionPerformed

    private void MItemDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemDActionPerformed
        // TO Manu Bar Doctor Menu Item Perform
        LoginDoctor dLog= new LoginDoctor();
        dLog.setVisible(true);
    }//GEN-LAST:event_MItemDActionPerformed

    private void MItemUserManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemUserManualActionPerformed
        // TO Manu Bar User Manual Menu Item Perform
        try {
        // Path to Word document
        File manual = new File("E:/Software Engineering/Semester 2/Assignments/PR/MediCareHospital/UserManual.docx");

        if (manual.exists()) {
            Desktop.getDesktop().open(manual);
        } else {
            JOptionPane.showMessageDialog(this, "User Manual file not found", "Error", JOptionPane.ERROR_MESSAGE);
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Unable to open User Manual", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }    
    }//GEN-LAST:event_MItemUserManualActionPerformed

    private void MItemNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemNActionPerformed
        // TO Manu Bar Nurse Menu Item Perform
        LoginNurse nLog = new LoginNurse();
        nLog.setVisible(true);
    }//GEN-LAST:event_MItemNActionPerformed

    private void MItemAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemAActionPerformed
        // TO Manu Bar Admin Menu Item Perform
        LoginAdmin aLog= new LoginAdmin();
        aLog.setVisible(true);
    }//GEN-LAST:event_MItemAActionPerformed

    private void MItemAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemAboutUsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, 
                "MediCare Hospital provides quality healthcare services including outpatient consultations, " + "\n"
                + "inpatient care, emergency services, and diagnostic procedures with care and responsibility. " + "\n"
                + "Our Hospital Management System helps doctors, nurses, and staff members " + "\n"
                + "(administator, receptionist etc) manage patient details and hospital work easily and efficiently" 
        );
    }//GEN-LAST:event_MItemAboutUsActionPerformed

    private void MItemContactUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MItemContactUsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, 
                "MediCare Hospital Head Branch: UK " + "\n"
                + "Concat Number: +4412345678" + "\n"
                + "Email: MedCareHospital@gmail.com" 
        );
    }//GEN-LAST:event_MItemContactUsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LoginMenu;
    private javax.swing.JMenuItem MItemA;
    private javax.swing.JMenuItem MItemAboutUs;
    private javax.swing.JMenuItem MItemClose;
    private javax.swing.JMenuItem MItemContactUs;
    private javax.swing.JMenuItem MItemD;
    private javax.swing.JMenuItem MItemL;
    private javax.swing.JMenuItem MItemN;
    private javax.swing.JMenuItem MItemUserManual;
    private javax.swing.JMenu MMore;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnLabTech;
    private javax.swing.JButton btnNurse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMovingText;
    private javax.swing.JPanel mainUIPanel;
    // End of variables declaration//GEN-END:variables
}
