/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Hospital.MedicalRecord;
import java.sql.Date;
import javax.swing.JOptionPane;
import Data.MedicalRecordFileDB;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class MedicalRecordUI extends javax.swing.JFrame {
    
    private MedicalRecord medRd; 
    private DefaultTableModel tblModel;
    private MedicalRecordFileDB mRfDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicalRecordUI.class.getName());

    /**
     * Creates new form MedicalRecordUI
     */
    public MedicalRecordUI() {
        initComponents();
        setLocationRelativeTo(this);
        mRfDB=new MedicalRecordFileDB();
        tblModel=new DefaultTableModel();
        tblmedRecord.setModel(tblModel);
        tblModel.addColumn("Record ID");
        tblModel.addColumn("Patient");
        tblModel.addColumn("Doctor");
        tblModel.addColumn("Visit Date");
        tblModel.addColumn("symptoms");
        tblModel.addColumn("Diagnosis");
        tblModel.addColumn("Treatment");
        tblModel.addColumn("Prescription");
        tblModel.addColumn("Test Result");
    }
    
    private boolean checkVal(){
        
        if (txtRecordID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Record ID cannot be blank");
            return false;
        }
        if (txtPatientID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Patient ID cannot be blank");
            return false;
        }
        if (txtVisitDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Visit Date cannot be blank");
            return false;
        }
        if (txtSymptoms.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Symptoms cannot be blank");
            return false;
        }
        if (txtDiagnosis.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Diagnosis cannot be blank");
            return false;
        }
        if (txtTreatment.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Treatment cannot be blank");
            return false;
        }
        if (txtPrescription.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Prescription cannot be blank");
            return false;
        }
        if (!rdoInProgress.isSelected() && !rdoPending.isSelected() && !rdoCompleted.isSelected()) {
            JOptionPane.showMessageDialog(this, "Select Test Result");
            return false;
        }
        try{
             Date visitDate=Date.valueOf(txtVisitDate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Visit Date must be YYYY-MM-DD");
            return false;
        }
        return true;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MedRecordPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRecordID = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtSymptoms = new javax.swing.JTextField();
        txtDiagnosis = new javax.swing.JTextField();
        txtTreatment = new javax.swing.JTextField();
        txtPrescription = new javax.swing.JTextField();
        cmbDoctorName = new javax.swing.JComboBox<>();
        txtVisitDate = new javax.swing.JTextField();
        rdoInProgress = new javax.swing.JRadioButton();
        rdoPending = new javax.swing.JRadioButton();
        rdoCompleted = new javax.swing.JRadioButton();
        MedRecordCmdPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmedRecord = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medical Record");
        setResizable(false);

        MedRecordPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Medical Record ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Record ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Patient ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Doctor Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Visit Date");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Symptoms");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Diagnosis");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Treatment");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Prescription");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Test Result");

        txtRecordID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPatientID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSymptoms.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtDiagnosis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTreatment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtPrescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbDoctorName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDoctorName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.James Wilson – General Physician", "Dr.Emily Parker – Pediatrician", "Dr.Oliver Brown – Cardiologist", "Dr.Amelia Wright – Dermatologist", "Dr.William Carter – Orthopedic Surgeon", "Dr.Charlotte Evans – Gynecologist" }));

        txtVisitDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        buttonGroup1.add(rdoInProgress);
        rdoInProgress.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoInProgress.setText("In Progress");
        rdoInProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoInProgressActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoPending);
        rdoPending.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoPending.setText("Pending");

        buttonGroup1.add(rdoCompleted);
        rdoCompleted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoCompleted.setText("Completed");

        MedRecordCmdPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add Record");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplay.setText("Display Record");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFind.setText("Find Record");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MedRecordCmdPanelLayout = new javax.swing.GroupLayout(MedRecordCmdPanel);
        MedRecordCmdPanel.setLayout(MedRecordCmdPanelLayout);
        MedRecordCmdPanelLayout.setHorizontalGroup(
            MedRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedRecordCmdPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(MedRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        MedRecordCmdPanelLayout.setVerticalGroup(
            MedRecordCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedRecordCmdPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnCancel)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnDisplay)
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblmedRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblmedRecord);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MedRecordPanelLayout = new javax.swing.GroupLayout(MedRecordPanel);
        MedRecordPanel.setLayout(MedRecordPanelLayout);
        MedRecordPanelLayout.setHorizontalGroup(
            MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MedRecordPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(MedRecordPanelLayout.createSequentialGroup()
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(27, 27, 27)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MedRecordPanelLayout.createSequentialGroup()
                                .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPatientID, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(txtRecordID))
                                .addGap(50, 50, 50)
                                .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVisitDate)))
                            .addComponent(txtDiagnosis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSymptoms)
                            .addGroup(MedRecordPanelLayout.createSequentialGroup()
                                .addComponent(rdoInProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoPending, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoCompleted)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtPrescription)
                            .addComponent(txtTreatment))
                        .addGap(58, 58, 58)
                        .addComponent(MedRecordCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MedRecordPanelLayout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MedRecordPanelLayout.setVerticalGroup(
            MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedRecordPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MedRecordPanelLayout.createSequentialGroup()
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtRecordID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MedRecordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rdoInProgress)
                            .addComponent(rdoPending)
                            .addComponent(rdoCompleted)))
                    .addComponent(MedRecordCmdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MedRecordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MedRecordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoInProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoInProgressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoInProgressActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TO Add Button Option
        if (checkVal()){ // stop if validation fails
            int recordID = Integer.valueOf(txtRecordID.getText());
            String patient = txtPatientID.getText();
            String doctor = cmbDoctorName.getSelectedItem().toString();
            Date visitDate=Date.valueOf(txtVisitDate.getText());
            String symptoms = txtSymptoms.getText();
            String diagnosis=txtDiagnosis.getText();
            String treatment=txtTreatment.getText();
            String prescription=txtPrescription.getText();

            String testResult="";
            if(rdoInProgress.isSelected()) {  
                testResult="In Progress";
            } else if (rdoPending.isSelected()){
                testResult="Pending";
            } else if (rdoCompleted.isSelected()){
                testResult="Completed";
            } else {
                testResult="";
            }

            medRd = new MedicalRecord(recordID, patient, doctor, visitDate, symptoms, diagnosis, treatment, prescription, testResult);
            if (mRfDB.createRecord(medRd))           
              JOptionPane.showMessageDialog(rootPane, "Medical Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "Medical Record is not added");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TO Cancel Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TO Display Button Option
        ArrayList<MedicalRecord> mList=mRfDB.getAll();
        tblModel.setRowCount(0);
        for(MedicalRecord medRd:mList){
            int mRID= medRd.getRecordID();
            String patient= medRd.getPatient();
            String doctor = medRd.getDoctor();
            Date visitDate = medRd.getVisitDate();
            String symptoms = medRd.getSymptoms();
            String diagnosis = medRd.getDiagnosis();
            String treatment = medRd.getTreatment();
            String prescription = medRd.getPrescription();
            String testResult = medRd.getTestResult();
            tblModel.addRow(new Object[]{mRID, patient, doctor, visitDate, symptoms, diagnosis, treatment, prescription, testResult});
        } 
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TO Find Button Option
        int mRID = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Medical Record ID"));
        MedicalRecord mR = mRfDB.findRecord(mRID);
        if (mR != null) {
            txtRecordID.setText(String.valueOf(mR.getRecordID()));
            txtPatientID.setText(mR.getPatient());
            cmbDoctorName.setSelectedItem(mR.getDoctor());
            txtVisitDate.setText(mR.getVisitDate().toString());
            txtSymptoms.setText(mR.getSymptoms());
            txtDiagnosis.setText(mR.getDiagnosis());
            txtTreatment.setText(mR.getTreatment());
            txtPrescription.setText(mR.getPrescription());

            // Set radio buttons
            if (mR.getTestResult().equals("In Progress")) {
                rdoInProgress.setSelected(true);
            } else if (mR.getTestResult().equals("Pending")) {
                rdoPending.setSelected(true);
            } else if (mR.getTestResult().equals("Completed")) {
                rdoCompleted.setSelected(true);
            }

            JOptionPane.showMessageDialog(rootPane, "Medical Record is Found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Medical Record is Not Found");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TO Update Button Option
        if (checkVal()){
            int recordID = Integer.valueOf(txtRecordID.getText());
            String patient = txtPatientID.getText();
            String doctor = cmbDoctorName.getSelectedItem().toString();
            Date visitDate=Date.valueOf(txtVisitDate.getText());
            String symptoms = txtSymptoms.getText();
            String diagnosis=txtDiagnosis.getText();
            String treatment=txtTreatment.getText();
            String prescription=txtPrescription.getText();

            String testResult="";
            if(rdoInProgress.isSelected()) {
                testResult="In Progress";
            } else if (rdoPending.isSelected()){
                testResult="Pending";
            } else if (rdoCompleted.isSelected()){
                testResult="Completed";
            } else {
                testResult="";
            }

            medRd = new MedicalRecord(recordID, patient, doctor, visitDate, symptoms, diagnosis, treatment, prescription, testResult);
            if (mRfDB.updateRecord(medRd))           
              JOptionPane.showMessageDialog(rootPane, "Medical Record Record is updated");
            else
               JOptionPane.showMessageDialog(rootPane, "Medical Record Record is not updated");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TO Delete Button Option
        int mRID=Integer.valueOf(JOptionPane.showInputDialog("Enter Medical Record ID"));
        if(mRfDB.cancelRecord(mRID))
            JOptionPane.showMessageDialog(rootPane, "Medical Record is deleted");
        else
             JOptionPane.showMessageDialog(rootPane, "Medical Record is not deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MedicalRecordUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MedRecordCmdPanel;
    private javax.swing.JPanel MedRecordPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDoctorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoCompleted;
    private javax.swing.JRadioButton rdoInProgress;
    private javax.swing.JRadioButton rdoPending;
    private javax.swing.JTable tblmedRecord;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPrescription;
    private javax.swing.JTextField txtRecordID;
    private javax.swing.JTextField txtSymptoms;
    private javax.swing.JTextField txtTreatment;
    private javax.swing.JTextField txtVisitDate;
    // End of variables declaration//GEN-END:variables
}
