/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;
import Hospital.MedicalStaff;
import Hospital.Person;
import Hospital.Staff;
import java.sql.Date;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Data.StaffFileDB;

/**
 *
 * @author USER
 */
public class MedicalStaffUI extends javax.swing.JFrame {
    
    private Staff Stf; // teh is a object
    private DefaultTableModel tblModel;
    private StaffFileDB sfDB;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicalStaffUI.class.getName());

    /**
     * Creates new form MedicalStaff
     */
    public MedicalStaffUI() {
        initComponents();
        setLocationRelativeTo(this);
        sfDB=new StaffFileDB();
        tblModel=new DefaultTableModel();
        tblMedStf.setModel(tblModel);
        tblModel.addColumn("Staff ID");
        tblModel.addColumn("Last Name");
        tblModel.addColumn("Gender");
        tblModel.addColumn("Contact Number");
        tblModel.addColumn("Department");
        tblModel.addColumn("Hire Date");
        tblModel.addColumn("Salary");
        tblModel.addColumn("WorkSchedule");
        tblModel.addColumn("Qualifications");
        tblModel.addColumn("Staff Type");
    }
    
    //To check each fields are not blank
    private boolean checkVal(){
        
        if (txtStaffID.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Staff ID cannot be blank");
            return false;
        }
        if (txtLastName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Last Name cannot be blank");
            return false;
        }
         if (txtContactNumber.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Contact Number cannot be blank");
            return false;
        }   
        if (txtHireDate.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Hire Date cannot be blank");
            return false;
        }
        if (txtSalary.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Salary cannot be blank");
            return false;
        }
        try{
             Date hireDate=Date.valueOf(txtHireDate.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Hire Date must be YYYY-MM-DD");
            return false;
        }  
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MediStfDetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbDepartment = new javax.swing.JComboBox<>();
        cmbQualification = new javax.swing.JComboBox<>();
        cmbStaffType = new javax.swing.JComboBox<>();
        txtStaffID = new javax.swing.JTextField();
        txtHireDate = new javax.swing.JTextField();
        MedStfCmdPanel = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtContactNumber = new javax.swing.JTextField();
        cmbWorkSchedule = new javax.swing.JComboBox<>();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedStf = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Madical Staff");

        MediStfDetailsPanel.setBackground(new java.awt.Color(255, 255, 255));
        MediStfDetailsPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Medical Staff Profile");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Department");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Hire Date");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("salary");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Work Schedule");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Qualifications");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Staff Type ");

        txtSalary.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Staff ID");

        cmbDepartment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPD", "Emergency Department", "General Medicine", "General Surgery", "Pediatrics" }));
        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        cmbQualification.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbQualification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MBBS", "Postgraduate Degree", "Diploma in Nursing", "BSc Nursing", "Allied Health Diploma or Degree" }));

        cmbStaffType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbStaffType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Allied Health Staff", "Administrative Staff" }));
        cmbStaffType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStaffTypeActionPerformed(evt);
            }
        });

        txtStaffID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtStaffID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaffIDActionPerformed(evt);
            }
        });

        txtHireDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        MedStfCmdPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCancel.setText("Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAdd.setText("Add Record");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDisplay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisplay.setText("Display Record");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFind.setText("Find Record");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnUpdate.setText("Update Record");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelete.setText("Delete Record");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MedStfCmdPanelLayout = new javax.swing.GroupLayout(MedStfCmdPanel);
        MedStfCmdPanel.setLayout(MedStfCmdPanelLayout);
        MedStfCmdPanelLayout.setHorizontalGroup(
            MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedStfCmdPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnUpdate))
                .addGap(28, 28, 28)
                .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        MedStfCmdPanelLayout.setVerticalGroup(
            MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MedStfCmdPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnCancel))
                .addGap(27, 27, 27)
                .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisplay)
                    .addComponent(btnFind))
                .addGap(26, 26, 26)
                .addGroup(MedStfCmdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Last Name");

        txtLastName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Gender");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Contact Number");

        txtContactNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbWorkSchedule.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbWorkSchedule.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day Shift", "Evening", "Night Shift" }));

        buttonGroup1.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoMale.setText("Male");
        rdoMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdoFemale.setText("Female");

        tblMedStf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMedStf);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MediStfDetailsPanelLayout = new javax.swing.GroupLayout(MediStfDetailsPanel);
        MediStfDetailsPanel.setLayout(MediStfDetailsPanelLayout);
        MediStfDetailsPanelLayout.setHorizontalGroup(
            MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MediStfDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2))
                                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtStaffID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(rdoMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rdoFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtContactNumber)))
                                .addGap(53, 53, 53)
                                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(36, 36, 36)
                                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbStaffType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSalary)
                                    .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHireDate)
                                    .addComponent(cmbWorkSchedule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(MedStfCmdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MediStfDetailsPanelLayout.setVerticalGroup(
            MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MediStfDetailsPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHireDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(cmbWorkSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdoMale)
                            .addComponent(rdoFemale))
                        .addGap(18, 18, 18)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(MediStfDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(cmbStaffType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MedStfCmdPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MediStfDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MediStfDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void txtStaffIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaffIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaffIDActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TO Exit Button Option
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TO Add Record Button Option
        if (checkVal()){
            int staffID = Integer.valueOf(txtStaffID.getText());
            String lastName = txtLastName.getText();
            
            String gender="";
            if(rdoMale.isSelected()) {
                gender="Male";
            } else if (rdoFemale.isSelected()){
                gender="Female";
            } else {
                gender="";
            }
            
            int contactNumber = Integer.valueOf(txtContactNumber.getText());
            String department = cmbDepartment.getSelectedItem().toString();
            Date hireDate=Date.valueOf(txtHireDate.getText());
            String salary=txtSalary.getText();
            String workSchedule = cmbWorkSchedule.getSelectedItem().toString();
            String qualifications = cmbQualification.getSelectedItem().toString();
            String staffType = cmbStaffType.getSelectedItem().toString();

            Stf = new Staff (staffID, lastName, gender, contactNumber, department, hireDate, salary, workSchedule, qualifications, staffType);
            if (sfDB.addRecord(Stf))           
              JOptionPane.showMessageDialog(rootPane, "Staff Record is added");
            else
               JOptionPane.showMessageDialog(rootPane, "Staff Record is not added");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TO Display Record Button Option 
        ArrayList<Staff> sList=sfDB.getAll();
        tblModel.setRowCount(0);
        for(Staff Stf:sList){
            int sID= Stf.getStaffID();
            String lastName= Stf.getLastName();
            String gender = Stf.getGender();
            int con= Stf.getContactNumber();
            String department = Stf.getDepartment();
            Date hireDate = Stf.getHireDate();
            String salary = Stf.getSalary();
            String workSchedule = Stf.getWorkSchedule();
            String qualifications = Stf.getQualifications();
            String staffType = Stf.getStaffType();
            tblModel.addRow(new Object[]{sID,lastName,gender,con,department,hireDate,salary,workSchedule,qualifications,staffType });
        } 
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TO Find Record Button Option
        int sID = Integer.valueOf(JOptionPane.showInputDialog(this, "Enter Staff ID"));
        Staff s = sfDB.findRecord(sID);
        if (s != null) {
            txtStaffID.setText(String.valueOf(s.getStaffID()));
            txtLastName.setText(s.getLastName());
            
            // Set radio buttons
            if (s.getGender().equals("Male")) {
                rdoMale.setSelected(true);
            } else if (s.getGender().equals("Female")) {
                rdoFemale.setSelected(true);
            } 
            
            txtContactNumber.setText(String.valueOf(s.getContactNumber()));
            cmbDepartment.setSelectedItem(s.getDepartment());
            txtHireDate.setText(s.getHireDate().toString());
            txtSalary.setText(s.getSalary());
            cmbWorkSchedule.setSelectedItem(s.getWorkSchedule());
            cmbQualification.setSelectedItem(s.getQualifications());
            cmbStaffType.setSelectedItem(s.getStaffType());

            JOptionPane.showMessageDialog(rootPane, "Staff Record is Found");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Staff Record is Not Found");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (checkVal()){
            int staffID = Integer.valueOf(txtStaffID.getText());
            String lastName = txtLastName.getText();
            
            String gender="";
            if(rdoMale.isSelected()) {
                gender="Male";
            } else if (rdoFemale.isSelected()){
                gender="Female";
            } else {
                gender="";
            }
            
            int contactNumber = Integer.valueOf(txtContactNumber.getText());
            String department = cmbDepartment.getSelectedItem().toString();
            Date hireDate=Date.valueOf(txtHireDate.getText());
            String salary=txtSalary.getText();
            String workSchedule = cmbWorkSchedule.getSelectedItem().toString();
            String qualifications = cmbQualification.getSelectedItem().toString();
            String staffType = cmbStaffType.getSelectedItem().toString();

            Stf = new Staff (staffID, lastName, gender, contactNumber, department, hireDate, salary, workSchedule, qualifications, staffType);
            if (sfDB.updateRecord(Stf))                
              JOptionPane.showMessageDialog(rootPane, "The Appointment Record is updated");
            else
               JOptionPane.showMessageDialog(rootPane, "The Appointment Record is not updated");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TO Delete Record button Option
        int sID=Integer.valueOf(JOptionPane.showInputDialog("Enter Staff ID"));
        if(sfDB.deleteRecord(sID))
            JOptionPane.showMessageDialog(rootPane, "Record is deleted");
        else
             JOptionPane.showMessageDialog(rootPane, "Record is not deleted");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void rdoMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoMaleActionPerformed

    private void cmbStaffTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStaffTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStaffTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MedicalStaffUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MedStfCmdPanel;
    private javax.swing.JPanel MediStfDetailsPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbQualification;
    private javax.swing.JComboBox<String> cmbStaffType;
    private javax.swing.JComboBox<String> cmbWorkSchedule;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JTable tblMedStf;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtHireDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
